---
- hosts: web
  become: yes
  tasks:
      - name: Install Apache
        apt:
           name: apache2
           state: latest
      - name: Index.html file creation
        copy:
            content: "Ansible Playbook!!"
            dest: /var/www/html/index.html
      - name: restart apache2
        service:
            name: apache2
            state: restarted
...
